export const ADD_COUNT = 'ADD_COUNT';
export const DOUBLE_COUNT = 'DOUBLE_COUNT';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const STORE_ALL_PRODUCTS = 'STORE_ALL_PRODUCTS';
export const STORE_LIMIT_PRODUCTS = 'STORE_LIMIT_PRODUCTS';

export const GET_CATEGORY = 'GET_CATEGORY';
export const STORE_PRODUCTS_CATEGORY = 'STORE_PRODUCTS_CATEGORY';

export const SET_CATEGORY_FILTER = 'SET_CATEGORY_FILTER';
export const SET_FILTER = 'SET_FILTER';
export const RESET_FILTERS = 'RESET_FILTERS';

export const SET_MIN_FILTER_PRICE = 'SET_MIN_FILTER_PRICE';
export const SET_MAX_FILTER_PRICE = 'SET_MAX_FILTER_PRICE';

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const UPDATE_PRODUCT_IN_CART = 'UPDATE_PRODUCT_IN_CART';

export const SET_INITIAL_CART = 'SET_INITIAL_CART';
